version: '3'

services:
  jenkins:
    user: root
    image: avsoftware/jenkins:latest
    ports:
      - 9090:8080
      - 50000:50000
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_data: