version: '3'

services:
  jenkins:
    image: avsoftware/jenkins:latest
    user: root
    environment:
      #- JAVA_OPTS=-Dhudson.footerURL=http://URL>
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Duser.timezone=Europe/London
      - JENKINS_USER=admin
      - JENKINS_PASS=admin
    ports:
      - 9090:8080
      - 8443:8443
      - 50000:50000
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      
  sonarqube:
    image: sonarqube: latest
    ports:
      - 9000:9000
    volumes:
      - sonar_conf:/opt/sonarqube/conf
      - sonar_data:/opt/sonarqube/data
      - sonar_logs:/opt/sonarqube/logs
      - sonar_extensions:/opt/sonarqube/extensions

volumes:
  jenkins_data:
  sonar_conf:
  sonar_data:
  sonar_logs:
  sonar_extensions:
