version: '3'

services:
  jenkins:
    image: avsoftware/jenkins:latest
    user: root
    environment:
      #- JAVA_OPTS=-Dhudson.footerURL=http://URL>
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Duser.timezone=Europe/London
      - JENKINS_USER=admin
      - JENKINS_PASS=admin
    ports:
      - 9090:8080
      - 8443:8443
      - 50000:50000
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      
  sonarqube:
    image: sonarqube:latest
    ports:
      - 9000:9000
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=v07IGCFCF83Z95NX
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
    volumes:
      - sonar_conf:/opt/sonar/conf
      - sonar_data:/opt/sonar/data
      - sonar_logs:/opt/sonar/logs
      - sonar_extensions:/opt/sonar/extensions
      - sonar_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  
  db:
    image: postgres:12.1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=v07IGCFCF83Z95NX
      - POSTGRES_DB=sonarqube
    volumes:
      - sonarqube_db:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:
  jenkins_data:
  sonar_bundled-plugins:
  sonar_db:
  sonar_conf:
  sonar_data:
  sonar_logs:
  sonar_extensions:
