version: '3'

services:
  jenkins:
    image: avsoftware/jenkins:latest
    environment:
      #- JAVA_OPTS=-Dhudson.footerURL=http://URL>
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Duser.timezone=Europe/London
      - JENKINS_USER=admin
      - JENKINS_PASS=admin
    ports:
      - 9090:8080
      - 8443:8443
      - 50000:50000
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_data:
